Import Necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import datetime as dt

Importing the dataset

In [2]:
df=pd.read_csv(r"C:\Users\areeb\OneDrive\Documents\VOIS Intern\Netflix\Netflix Dataset.csv")

In [3]:
df.head()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
df.tail()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
7784,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7785,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7786,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7787,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7788,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [5]:
df.info

<bound method DataFrame.info of      Show_Id Category                                    Title  \
0         s1  TV Show                                       3%
1         s2    Movie                                    07:19
2         s3    Movie                                    23:59
3         s4    Movie                                        9
4         s5    Movie                                       21
...      ...      ...                                      ...
7784   s7783    Movie                                     Zozo
7785   s7784    Movie                                   Zubaan
7786   s7785    Movie                        Zulu Man in Japan
7787   s7786  TV Show                    Zumbo's Just Desserts
7788   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS

               Director                                               Cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...
...                 ...                                                ...
7784        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...
7785        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
7786                NaN                                            Nasty C
7787                NaN                         Adriano Zumbo, Rachel Khoo
7788           Sam Dunn                                                NaN

                                                Country        Release_Date  \
0                                                Brazil     August 14, 2020
1                                                Mexico   December 23, 2016
2                                             Singapore   December 20, 2018
3                                         United States   November 16, 2017
4                                         United States     January 1, 2020
...                                                 ...                 ...
7784  Sweden, Czech Republic, United Kingdom, Denmar...    October 19, 2020
7785                                              India       March 2, 2019
7786                                                NaN  September 25, 2020
7787                                          Australia    October 31, 2020
7788              United Kingdom, Canada, United States       March 1, 2020

     Rating   Duration                                               Type  \
0     TV-MA  4 Seasons  International TV Shows, TV Dramas, TV Sci-Fi &...
1     TV-MA     93 min                       Dramas, International Movies
2         R     78 min                Horror Movies, International Movies
3     PG-13     80 min  Action & Adventure, Independent Movies, Sci-Fi...
4     PG-13    123 min                                             Dramas
...     ...        ...                                                ...
7784  TV-MA     99 min                       Dramas, International Movies
7785  TV-14    111 min     Dramas, International Movies, Music & Musicals
7786  TV-MA     44 min  Documentaries, International Movies, Music & M...
7787  TV-PG   1 Season                 International TV Shows, Reality TV
7788  TV-MA     90 min                    Documentaries, Music & Musicals

                                            Description
0     In a future where the elite inhabit an island ...
1     After a devastating earthquake hits Mexico Cit...
2     When an army recruit is found dead, his fellow...
3     In a postapocalyptic world, rag-doll robots hi...
4     A brilliant group of students become card-coun...
...                                                 ...
7784  When Lebanon's Civil War deprives Zozo of his ...
7785  A scrappy but poor boy worms his way into a ty...
7786  In this documentary, South African rapper Nast...
7787  Dessert wizard Adriano Zumbo looks for the nex...
7788  This documentary delves into the mystique behi...

[7789 rows x 11 columns]>

In [6]:
df.describe()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
count,7789,7789,7789,5401,7071,7282,7779,7782,7789,7789,7789
unique,7787,2,7787,4050,6831,681,1565,14,216,492,7769
top,s684,Movie,Backfire,"Raúl Campos, Jan Suter",David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,Documentaries,Multiple women report their husbands as missin...
freq,2,5379,2,18,18,2556,118,2865,1608,334,3

In [7]:
df.isnull().sum()

Show_Id            0
Category           0
Title              0
Director        2388
Cast             718
Country          507
Release_Date      10
Rating             7
Duration           0
Type               0
Description        0
dtype: int64

Performing EDA on the Dataset including Cleaning the dataset

In [8]:
df.duplicated().sum()

np.int64(2)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7789 entries, 0 to 7788
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_Id       7789 non-null   object
 1   Category      7789 non-null   object
 2   Title         7789 non-null   object
 3   Director      5401 non-null   object
 4   Cast          7071 non-null   object
 5   Country       7282 non-null   object
 6   Release_Date  7779 non-null   object
 7   Rating        7782 non-null   object
 8   Duration      7789 non-null   object
 9   Type          7789 non-null   object
 10  Description   7789 non-null   object
dtypes: object(11)
memory usage: 669.5+ KB

In [10]:
df['Show_Id'].unique()

array(['s1', 's2', 's3', ..., 's7785', 's7786', 's7787'],
      shape=(7787,), dtype=object)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

Show_Id         object
Category        object
Title           object
Director        object
Cast            object
Country         object
Release_Date    object
Rating          object
Duration        object
Type            object
Description     object
dtype: object

In [14]:
df.duplicated().value_counts()

False    7787
Name: count, dtype: int64

In [15]:
df.drop(['Director', 'Cast'], axis=1, inplace=True)

In [16]:
df.head()

,Show_Id,Category,Title,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [17]:
df['Country'].value_counts()

Country
United States                                     2555
India                                              923
United Kingdom                                     397
Japan                                              226
South Korea                                        183
                                                  ...
Germany, United States, United Kingdom, Canada       1
Peru, United States, United Kingdom                  1
Saudi Arabia, United Arab Emirates                   1
United Kingdom, France, United States, Belgium       1
France, Norway, Lebanon, Belgium                     1
Name: count, Length: 681, dtype: int64

In [18]:
df.isnull().sum()

Show_Id           0
Category          0
Title             0
Country         507
Release_Date     10
Rating            7
Duration          0
Type              0
Description       0
dtype: int64

In [19]:
df['Rating'].value_counts()

Rating
TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
TV-Y7-FV       6
UR             5
NC-17          3
Name: count, dtype: int64

In [20]:
df['Release_Date'].value_counts()

Release_Date
January 1, 2020      118
November 1, 2019      94
March 1, 2018         76
December 31, 2019     76
October 1, 2018       72
                    ...
November 7, 2014       1
February 25, 2018      1
July 4, 2017           1
November 16, 2017      1
January 11, 2020       1
Name: count, Length: 1565, dtype: int64

In [21]:
df['Release_Date'] = pd.to_datetime(df['Release_Date'], errors='coerce')

In [22]:
df['Release_Date'].value_counts()
df.dropna(subset=['Release_Date'], inplace=True)

Converting and Separating Release Date into different columns of Date, Month and Year

In [23]:
df['Year'] = df['Release_Date'].dt.year
df['Month'] = df['Release_Date'].dt.month
df['Day'] = df['Release_Date'].dt.day

In [24]:
df.isnull().sum()

Show_Id           0
Category          0
Title             0
Country         503
Release_Date      0
Rating            7
Duration          0
Type              0
Description       0
Year              0
Month             0
Day               0
dtype: int64

In [25]:
df['Rating'].dropna (inplace=True)

In [26]:
df.isnull().sum()

Show_Id           0
Category          0
Title             0
Country         503
Release_Date      0
Rating            7
Duration          0
Type              0
Description       0
Year              0
Month             0
Day               0
dtype: int64

In [27]:
df['Country'].fillna(df['Country'].mode()[0], inplace=True)

In [28]:
df.isnull().sum()

Show_Id         0
Category        0
Title           0
Country         0
Release_Date    0
Rating          7
Duration        0
Type            0
Description     0
Year            0
Month           0
Day             0
dtype: int64

Using Label Encoding to encode Ordinal Data like Country

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
le=LabelEncoder()

In [31]:
df['Country'] = le.fit_transform(df['Country'])

In [32]:
df.head()

,Show_Id,Category,Title,Country,Release_Date,Rating,Duration,Type,Description,Year,Month,Day
0,s1,TV Show,3%,39,2020-08-14,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020,8,14
1,s2,Movie,07:19,306,2016-12-23,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016,12,23
2,s3,Movie,23:59,377,2018-12-20,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018,12,20
3,s4,Movie,9,546,2017-11-16,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017,11,16
4,s5,Movie,21,546,2020-01-01,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020,1,1

In [33]:
df['Country'].unique()

array([ 39, 306, 377, 546, 445, 137, 229, 355, 441, 328, 336, 459, 289,
       392, 275,  51, 249, 360, 400, 227, 388, 147, 637, 358, 221, 593,
       386,   0, 590, 193, 125, 353, 294, 325, 340,  12,  26, 312, 573,
        97, 436, 649, 183, 562, 534, 320,  78, 121, 219, 177,  94, 348,
       530, 457, 315, 500, 255, 655, 485,   1, 274, 622, 668, 378, 540,
       450,  47,  15, 223, 452, 571, 201, 305, 618, 297, 560, 109, 666,
       138, 164, 665, 399, 429, 384, 303, 266, 415, 487, 595, 607, 292,
       135, 389,  67, 376,  69, 228, 257, 616, 141, 233, 103, 402, 472,
        43, 159, 247, 150, 252, 330, 345, 182,  55,  86, 362,  48, 427,
       215, 190,  24, 381, 291, 370,  13, 582, 332, 314, 308, 549, 365,
        14, 505,  35, 324, 671, 394, 567, 236, 588, 481, 448, 350, 674,
       261, 372, 368, 523,   7, 204, 220,   8, 155, 208, 132, 263, 606,
       456, 425, 335, 142, 131, 522, 650, 245, 568,  75, 614, 248, 473,
       251, 319, 397, 349, 175, 296, 519, 256, 179, 535, 477, 550,  96,
       205, 644,  79, 232, 466, 608, 565, 438,  41, 547, 447,  20, 211,
       167, 307, 287, 200,  84, 468, 117, 676, 488, 439, 106,  54, 461,
       226, 194, 521,  46, 352, 143, 647, 403, 136, 525, 145, 502, 391,
       181, 148, 617, 124, 551, 476, 366, 163, 639, 196,  87, 108, 341,
       510, 351, 563, 672,  10, 623, 112,  45, 120,  56,  74, 225, 160,
       611, 407, 418, 410, 411, 583, 269, 278, 470,  50, 100, 458,   6,
       507, 282, 406, 557, 589, 630,  29, 454, 187, 544, 153, 284,  40,
       244, 295, 638, 398, 277, 444, 478, 316, 471, 592, 654, 659, 586,
       670, 195, 660, 651, 283, 369, 566, 578, 267, 648, 149, 222, 301,
       640, 364, 675, 612,  90, 265,  34, 354, 382,  76, 539, 253, 642,
       237, 432, 102, 482,  64, 538, 636, 207, 570,  80, 494,   4, 387,
        85, 144, 657, 437,  49, 419, 268, 293,  27, 209, 495, 585, 250,
       318, 107, 151, 422, 572,  32, 518, 619, 333,  99, 548, 313, 111,
       464, 329, 527, 646, 317, 158, 490, 130, 123, 304, 339, 633, 601,
       188, 552,  71, 508, 206, 105,   3, 635, 669, 446, 576,  59,   9,
       186, 104, 285, 356, 213,  73, 484, 169, 322, 561, 600, 575, 643,
       338, 555, 520,  95, 641, 239, 545, 343, 273,  93, 176, 493, 192,
       431, 449, 280, 556, 577,  88, 359, 631, 210, 414, 542, 323, 609,
       127, 128, 184, 337, 613, 524, 413, 199, 122,  42, 234, 286, 126,
        18, 101, 405,  21,  81, 152, 532, 673, 173, 240, 311, 113, 110,
       166, 198,  61, 342, 185, 423, 512, 632,  83, 435, 357, 170, 627,
       628, 626, 243,  62,  66, 625, 624, 331, 393, 379,  68, 536, 202,
       346, 380, 663, 231, 259, 594, 374, 271,  16, 385,  28,  17, 653,
       428, 224, 662, 395, 218, 451, 652, 281, 480, 390, 598, 242, 279,
        57, 238, 434, 442,  98, 516, 489, 396, 119,  23,  77, 604, 288,
       430,  25, 189,  22, 580, 486, 134,  33, 116, 302, 603, 620,   5,
       597, 599, 629, 146, 412, 156, 162, 401, 504,  89, 656,  70, 605,
       564, 514, 258, 579, 216, 270, 417, 309,  44, 154, 272, 165, 621,
       541,  31, 217, 483,  52,   2, 118, 499, 513, 140, 408, 602, 475,
       440, 645, 543, 661, 574, 404,  53, 610, 467, 421,  60, 235, 615,
       501, 299,  36,  91, 344, 509, 334, 161, 321, 171, 264, 129, 327,
        11, 498, 553, 276, 596,  92, 203, 517,  38,  19, 420, 254,  72,
       168, 114, 383, 260, 424, 569, 529, 375, 133, 197, 262,  58, 409,
       246, 554, 584, 479, 497, 492, 531, 587, 191, 658, 326, 634, 455,
       462, 310, 416, 212, 664, 469,  65, 537, 474, 465, 443, 515, 526,
        82, 559, 172, 511, 433,  37, 496, 363, 300, 503, 463, 241, 460,
       371, 157, 558, 506, 298, 230,  30, 180, 491, 373, 347, 214, 667,
       174, 528,  63, 361, 581, 178, 533, 139, 367, 115, 290, 591, 453,
       426])